spring.application.name=simpleboard

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/simpleboard}
spring.datasource.username=${DB_USERNAME:simpleboard}
spring.datasource.password=${DB_PASSWORD:simpleboard}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.thymeleaf.cache=false

server.port=8080